### PR TITLE
Fix browser example configuration

### PR DESCRIPTION
**Pull request by magnetised**
see https://github.com/electric-sql/typescript-client/pull/26

- [x] update migrations after https://github.com/electric-sql/typescript-client/pull/25 is merged
- [ ] bump typescript client version

### CODE REVIEW

**Review by balegas — COMMENTED** [review]
Is this required for current typescript-client, or just with https://github.com/electric-sql/typescript-client/pull/26?

**Comment by balegas** [comment]
I suppose from the comment it is just with the PR.
Please:
- [ ] merge the first one when ready
- [ ] make a new release
- [ ] update the examples in this PR to use the new release

**Review by balegas — APPROVED** [review]
All good on my side.
Please bump the dependency version before merging.

**Comment by magnetised** [comment]
@balegas think this is now good to go

**Comment by thruflo** [comment]
Is this good to merge?

**Comment by balegas** [comment]
All good from my side Garry. Please merge.

**Pull request merged**
